### ISSUE TITLE
[Thread] How to define blocklet scripts

### ISSUE THREAD

**Issue by wangshijun** [blocklet/blocklet-specification#3]
## 问题来源

https://github.com/blocklet/blocklet-specification/pull/1

## 问题描述

Blocklet 不同环境下、不同平台下需要 abtnode 帮其执行的脚本可能会有所不同，如何标准化定义？

## 解决方案

```yml
scripts:
	- name: "dev"
	  command: "npm run dev"
	- name: "run"
	  command: "/path/to/executable-linux"
	  platform: "linux"
	- name: "run"
	  command: "/path/to/executable-mac"
	  platform: "mac"
	- name: "serve"
	  command: "/path/to/executable-mac"
	- name: "build"
	  command: "npm run build"
	- name: "bundle"
	  command: "abtnode bundle --zip"
```

这么设计是为了跨平台，而如果 scripts 本身就是跨平台的，那么可以简写成：

```yml
scripts:
	dev: "npm run dev"
	run: "/path/to/executable"
	build: "npm run build"
	bundle: "abtnode bundle --zip"
	serve: "/path/to/static-folder"
```

之所以设计 `run` 和 `serve` 是想把原来的 `group` 和 `main` 字段给废弃掉，这样 `run` 就是执行这个 blocklet，而 `serve` 就是通过内置的 web-server 去提供静态内容。
